apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:storage-provisioner-minikube-fixed
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-provisioner-minikube-fixed-binding
subjects:
- kind: ServiceAccount
  name: storage-provisioner
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:storage-provisioner-minikube-fixed
  apiGroup: rbac.authorization.k8s.io